### ISSUE TITLE
Fazer o Diagrama de Entidade Relacionamento (DER)

### ISSUE THREAD

**Issue by andrebaltieri** [andrebaltieri/AgendaEventos#12]

**Comment by andrebaltieri** [comment]
References #11

**Comment by jenrodrigues** [comment]
@BrewertonSantos e @colussicode vao trabalhar nessa tarefa na quinta-feira 29/04 e compartilhar o primeiro esboco com o resto do time.

**Comment by pedropagotto** [comment]
@BrewertonSantos , segue como sugestão de ferramenta para geração do diagrama:

https://mermaid-js.github.io/mermaid/#/classDiagram

é bem legal pois ela integra via markdown, e também da para fazer diagramas escrevendo.

acredito que vai facilitar na hora de vincular na wiki do projeto ao inves de colocar print ou arquivo por exemplo.

**Comment by BrewertonSantos** [comment]
Foi movido por engano.

**Comment by jenrodrigues** [comment]
Pessoal, primeiro esboco da modelagem de entidades/classes (sei la, nao tenho certeza de qual e qual :D ) criado por @BrewertonSantos, @colussicode e @JoaoNascSilva e @GabrielNalin segue. Precisamos de feedback: 
![DiagramaEntidadeClasse_V1 0](https://user-images.githubusercontent.com/31799846/116700694-f7ba6380-a9be-11eb-9f8f-f13493eb29cc.png)

**Comment by BrewertonSantos** [comment]
> @BrewertonSantos , segue como sugestão de ferramenta para geração do diagrama:
> 
> https://mermaid-js.github.io/mermaid/#/classDiagram
> 
> é bem legal pois ela integra via markdown, e também da para fazer diagramas escrevendo.
> 
> acredito que vai facilitar na hora de vincular na wiki do projeto ao inves de colocar print ou arquivo por exemplo.

Li agora e gostei, começarei a fazser desta forma. Obrigado @pedropagotto .

**Comment by BrewertonSantos** [comment]
> Pessoal, primeiro esboco da modelagem de entidades/classes (sei la, nao tenho certeza de qual e qual :D ) criado por @BrewertonSantos, @colussicode e @JoaoNascSilva e @GabrielNalin segue. Precisamos de feedback:
> 
> ![DiagramaEntidadeClasse_V1 0](https://user-images.githubusercontent.com/31799846/116700694-f7ba6380-a9be-11eb-9f8f-f13493eb29cc.png)
> 
> Na minha opiniao acho que voces fizeram ate alem do que o @andrebaltieri pediu! Pelo que eu entendi da nossa ultima reuniao com ele, propriedades e metodos nao eram necessarios nesse momento.
> Acho que a entidade Pessoa poderia ser chamada de Participante (dai um Usuario pode ser do tipo Administrador, Participante ou Organizador) e na minha opiniao falta um relacionamento entre Organizador e Evento (porque o primeiro gerencia o segundo). No mais eu acho que ficou muito bom e estamos caminhando muito bem.

Boas colocações @jenrodrigues . Modificaremos ele para atender. Sobre os métodos, não colocamos todos que iriam(deixamos para a reunião). Estes ai são referêntes as US existentes.

**Comment by jenrodrigues** [comment]
Anexando uma outra versao pra agregar no debate MER x VER x QUARQUER x SEI LA.

![EntityRelationshipModel_V1 0](https://user-images.githubusercontent.com/31799846/116736085-51cf1f00-a9e7-11eb-8582-df9b9438d5ea.png)

**Comment by jenrodrigues** [comment]
Apos a reuniao de 3 de maio, renomeei o titulo da issue pra ficar mais de acordo com o que o Balta pediu. Criei uma nova issue (#45) pra tratar exclusivamente do Modelo de Entidade Relacionamento.

**Comment by jenrodrigues** [comment]
@andrebaltieri @BrewertonSantos , segue nova versao do DER, de acordo com o que o grupo conversou em 3 de maio. Por favor avisem se nao estiverem de acordo com algo: 
![EntityRelationshipModel_V1 1](https://user-images.githubusercontent.com/31799846/116977694-a52cc000-acba-11eb-930b-0dbcf8b5b13a.png)

**Comment by jenrodrigues** [comment]
Ultima versao aprovada pelo time dev na reuniao do dia 5 de maio.

**Comment by jenrodrigues** [comment]
Fechando issue segundo recomendacao do Balta em 6 de maio.
