### ISSUE TITLE
Ao tentar incluir uma nova role, API exige o preenchimento de dados de usuario

### ISSUE THREAD

**Issue by jenrodrigues** [andrebaltieri/AgendaEventos#122]
Branch onde o teste foi efetuado: main

Url: https://localhost:5001/api/v1/roles

Request: 
{"title": "role de teste 2", 
"description": "descricao pro role de teste",
"users": [{}]
}

Resposta: 
![image](https://user-images.githubusercontent.com/31799846/124091855-2a7be900-da4e-11eb-9426-00d9930d23f0.png)

**Comment by JoaoNascSilva** [comment]
Neste caso necessita enviar desta forma

Request:
{
  "title": "role de teste 2",
  "description": "descricao pro role de teste"
}

**Comment by jenrodrigues** [comment]
Testado na branch main. Bug resolvido.
