### ISSUE TITLE
Inclusao de novo usuario obriga o preenchimento de um id, retorna erro 500 mas confirma registro novo no bd

### ISSUE THREAD

**Issue by jenrodrigues** [andrebaltieri/AgendaEventos#126]
Branch onde o teste foi efetuado: main

Url: https://localhost:5001/api/v1/users/

Request: 
{"email": "teste2@teste.com",
"name": "Teste da Silva 2",
"password": "teste",
"roles": [{
    "id": 6,
    "title": "Organizador",
    "description": "Cria e organiza eventos."
    }
]}

Resposta: 
![image](https://user-images.githubusercontent.com/31799846/124098975-f821ba00-da54-11eb-9d20-66a8e6c457bd.png)

![image](https://user-images.githubusercontent.com/31799846/124099034-05d73f80-da55-11eb-87fc-f15d946dc7f6.png)

**Comment by JoaoNascSilva** [comment]
Realmente obriga a informar uma role já no cadastro.
Isto se deve por conta do modelo de dados que estamos utilizando atualmente.
Em um futuro próximo podemos refatorar e adotar uma nova abordagem, por exemplo, utilizando domínios ricos.

**Comment by renebentes** [comment]
> Realmente obriga a informar uma role já no cadastro.
> Isto se deve por conta do modelo de dados que estamos utilizando atualmente.
> Em um futuro próximo podemos refatorar e adotar uma nova abordagem, por exemplo, utilizando domínios ricos.

De acordo

**Comment by jenrodrigues** [comment]
Testei na branch main. Bug resolvido.
