### ISSUE TITLE
Criar console app no VSCode com a estrutura de classes proposta

### ISSUE THREAD

**Issue by jenrodrigues** [andrebaltieri/AgendaEventos#16]

**Comment by jenrodrigues** [comment]
Testando referencia dentro de uma issue a um item aberto no GitHub Discussions: #35

**Comment by jenrodrigues** [comment]
Utilizar DER(#12 ), MER(#45) e diagrama de classes(#46) como apoio.

**Comment by jenrodrigues** [comment]
Commits enviados para o repositorio do @LuanFreitasRibeiro . Quem quiser revisar o que foi criado: https://github.com/LuanFreitasRibeiro/AgendaConsoleApp/tree/develop

**Comment by LeonardoPedrosa** [comment]
Show de bola, pessoal. Depois damos um tapa para usarmos VOs. 
Acredito que atenda demais para o que será demonstrado hoje ao Balta.

**Comment by jenrodrigues** [comment]
Revisado e aprovado pelo Balta em 24 de maio.
