### ISSUE TITLE
Criar os scripts da base de dados

### ISSUE THREAD

**Issue by jenrodrigues** [andrebaltieri/AgendaEventos#17]
Criar o script da base de dados com base nas classes criadas na issue #16 .

**Comment by jenrodrigues** [comment]
Segue a primeira versao. @LeonardoPedrosa @JoaoNascSilva @colussicode por favor deixem feedback:

[DBCreation_Agenda_V1.0.txt](https://github.com/andrebaltieri/AgendaEventos/files/6462549/DBCreation_Agenda_V1.0.txt)

**Comment by BrewertonSantos** [comment]
> Segue a primeira versao. @LeonardoPedrosa @JoaoNascSilva @colussicode por favor deixem feedback:
> 
> [DBCreation_Agenda_V1.0.txt](https://github.com/andrebaltieri/AgendaEventos/files/6462549/DBCreation_Agenda_V1.0.txt)

Eu discordo com a forma que foi apresentado. Penso assim: O git tem como um de seus fortes o versionamento de código e ótimos recursos para isto desde a versão inicial até a final. Então estamos regredindo quando fazemos por exemplo como foi mostrado lá(arquivo para download. Minha opinião: 

Enviar o código inicial através de um pull request;
Adicionar comentários que considerar relevantes e uma discussão pode ser iniciada dentro do pull request mesmo (sem necessidade de criar issue ou tópico no discussion);
Após todo o desenvolvimento da discussão, aprovar (ou não) o pull request.

**Comment by renebentes** [comment]
> Segue a primeira versao. @LeonardoPedrosa @JoaoNascSilva @colussicode por favor deixem feedback:
> 
> [DBCreation_Agenda_V1.0.txt](https://github.com/andrebaltieri/AgendaEventos/files/6462549/DBCreation_Agenda_V1.0.txt)

Bom trabalho @jenrodrigues. Tenho apenas duas colocações:

- Vamos usar nvarchar para tudo? A agenda vai ser multi-idiomas?
- Creio que para os campos Url e Banner na tabela Event não são suficientes, pois se levarmos em consideração que esses links viriam de outra plataforma, como um CDN para o banner, vai truncar quando salvar.

No mais é isso mesmo, está condizente com o modelo de dados que levantamos anteriormente.

**Comment by JoaoNascSilva** [comment]
também notei os mesmos casos citados anteriormente pelo @BrewertonSantos e @renebentes, do mais de acordo com o modelo apresentado.

**Comment by LeonardoPedrosa** [comment]
Acredito que seja isso mesmo @jenrodrigues.
Concordo quanto ao versionamento proposto por @BrewertonSantos.
E também concordo com o @renebentes com os pontos levantados.

Parabéns pela iniciativa de pegar pra você e fazer acontecer.

**Comment by jenrodrigues** [comment]
PessoALL, acabo de subir uma nova PR pro @LuanFreitasRibeiro avaliar. Mudancas em relacao a versao 1.0 do script: 
- Mudei o tipo NVARCHAR pra VARCHAR
- Mudei os tamanhos dos campos url e banner da tabela Event para VARCHAR(500)

Por favor avisem se tiverem mais alguma sugestao de melhoria.

**Comment by jenrodrigues** [comment]
Revisado e aprovado pelo Balta em 24 de maio.
