### ISSUE TITLE
Meeting 13/04 21h 

### ISSUE THREAD

**Issue by jenrodrigues** [andrebaltieri/AgendaEventos#2]
O @nicolasbcp avisou no Discord que ha uma meeting agendado pra hoje as 21h, mas o horario dessa meeting vai conflitar com a live do Balta. Preferem reagendar a meeting do projeto ou manter?

**Comment by LuanFreitasRibeiro** [comment]
Acho que seria interessante reagendar, ou para outro horário ou para amanhã.

**Comment by BrewertonSantos** [comment]
Sim, podemos agendar para a quarta. O que acham?
Mais uma coisa, pessoal! Existe uma opção chamada discussions no github. Podemos conversar para discutirmos tudo por lá. Os issues tem outro objetivo. O que acham?

**Comment by colussicode** [comment]
Eu acho interessante reagendar também, acho que esse encontro do balta é importante.

**Comment by gfilenga** [comment]
Quarta no mesmo horário ta perfeito

Em ter, 13 de abr de 2021 às 13:05, colussi ***@***.***>
escreveu:

**Comment by jenrodrigues** [comment]
Tambem voto por quarta-feira 14/04. 
Se puderem trazer para 20h ao inves de 21h melhor ainda pra mim. Senao, concordo com 14/04 as 21h.

**Comment by BrewertonSantos** [comment]
As 20 não é possível para mim :disappointed:

**Comment by GabrielNalin** [comment]
Por mim, pode remarcar sem problemas

Em ter, 13 de abr de 2021 12:42, Jenifer Rodrigues ***@***.***>
escreveu:

**Comment by nicolasbcp** [comment]
Pessoal, pelo que vi aqui a maioria optou por reagendar mesmo para **quarta-feira às 21h**, vou marcar todos apenas pra dar ciência e encerrarmos a Issue.

Caso alguém **_não_** concordar com a data, adiciona um novo comentário pls.

@renebentes 
@LeonardoPedrosa 
@jenrodrigues 
@JoaoNascSilva 
@LuanFreitasRibeiro 
@colussicode 
@lucasmiranda0 
@BrewertonSantos 
@nilson-teodoro 
@gfilenga 
@GabrielNalin

**Comment by BrewertonSantos** [comment]
:heavy_check_mark: Confirmado!

**Comment by LeonardoPedrosa** [comment]
Sobre a remarcação desse primeiro ponto eu não vejo nenhum problema. 
Mas se a gente for tentar alinhar o horário de todos em reuniões de alinhamentos, sempre vai acontecer esse tipo de situação de remarcação. Apenas um adendo para pensarmos nas próximas.

**Comment by LeonardoPedrosa** [comment]
> Mais uma coisa, pessoal! Existe uma opção chamada discussions no github. Podemos conversar para discutirmos tudo por lá. Os issues tem outro objetivo. O que acham?
Que assim seja. 
Boas práticas sempre.

**Comment by BrewertonSantos** [comment]
Pessoal, reajam com :+1:  no comentário do @nicolasbcp caso concordem para termos certeza que viram. 

> Pessoal, pelo que vi aqui a maioria optou por reagendar mesmo para **quarta-feira às 21h**, vou marcar todos apenas pra dar ciência e encerrarmos a Issue.
> 
> Caso alguém **_não_** concordar com a data, adiciona um novo comentário pls.
> 
> @renebentes
> @LeonardoPedrosa
> @jenrodrigues
> @JoaoNascSilva
> @LuanFreitasRibeiro
> @colussicode
> @lucasmiranda0
> @BrewertonSantos
> @nilson-teodoro
> @gfilenga
> @GabrielNalin

**Comment by LuanFreitasRibeiro** [comment]
> Sobre a remarcação desse primeiro ponto eu não vejo nenhum problema.
> Mas se a gente for tentar alinhar o horário de todos em reuniões de alinhamentos, sempre vai acontecer esse tipo de situação de remarcação.
> Apenas um adendo para pensarmos nas próximas.

Neste caso, é porque marcamos e não vimos que teríamos o encontro Premium do Balta hoje. Mas eu concordo contigo.

**Comment by GabrielNalin** [comment]
Concordo.Podemos deixar marcado para um dia fixo toda semana. Talvez uma
votação seria bem vinda.
Por mim, preferencialmente de segunda ou quinta...
Sabe se os eventos do Balta são todas às terças?

Em ter, 13 de abr de 2021 14:45, Luan Freitas ***@***.***>
escreveu:

**Comment by renebentes** [comment]
Concordo com a remarcação, mas acho que deveria ser uma hora mais cedo as próximas. Para evitar estender até mais tarde. Lembrem-se que todos trabalhamos no dia seguinte.

**Comment by LuanFreitasRibeiro** [comment]
> Concordo com a remarcação, mas acho que deveria ser uma hora mais cedo as próximas. Para evitar estender até mais tarde. Lembrem-se que todos trabalhamos no dia seguinte.

Uma hora mais cedo eu não conseguiria participar, pelo menos não todo dia.
