### ISSUE TITLE
Fazer o Modelo de Entidade Relacionamento (MER)

### ISSUE THREAD

**Issue by jenrodrigues** [andrebaltieri/AgendaEventos#45]
Utilizar a versao mais recente do DER disponivel em #12 .

**Comment by jenrodrigues** [comment]
Versao 1.0, criada antes da reuniao do dia 3 de maio: 
![EntityRelationshipModel_V1 0](https://user-images.githubusercontent.com/31799846/116986406-a8797900-acc5-11eb-9e3b-ce263e6f6e51.png)

**Comment by jenrodrigues** [comment]
Versao 1.0, criada apos a reuniao do dia 3 de maio. 
![EntityRelationshipModel_V1 1](https://user-images.githubusercontent.com/31799846/116986572-d959ae00-acc5-11eb-8e3a-1609a6050c43.png)

**Comment by renebentes** [comment]
Para mim está de acordo com o que foi debatido na reunião

**Comment by BrewertonSantos** [comment]
Eu gosto de pensar que a apresentação do material também é algo interessante. Mesmo esta não sendo uma prioridade. Já que fizemos, melhorar a apresentação também.

**Comment by BrewertonSantos** [comment]
Outro ponto é, palestrate foi conversado? Se forem vários palestrantes a demonstração não ficaria assim. Certo?

**Comment by jenrodrigues** [comment]
Ultima versao aprovada pelo time dev em reuniao do dia 5 de maio.

**Comment by jenrodrigues** [comment]
Fechando issue segundo recomendacao do Balta em 6 de maio.
