### ISSUE TITLE
Criar o diagrama de classes

### ISSUE THREAD

**Issue by jenrodrigues** [andrebaltieri/AgendaEventos#46]

**Comment by jenrodrigues** [comment]
Versao 1.0 do diagrama de classes, de antes da reuniao do dia 3 de maio: 
![ClassDiagram_V1 0](https://user-images.githubusercontent.com/31799846/117043967-c6ff6480-ad05-11eb-8e0c-d9bb208640f7.png)

**Comment by jenrodrigues** [comment]
Versao 1.1 do diagrama de classes, feito apos a troca de ideias na reuniao do dia 3 de maio. Precisamos de feedback ok? @BrewertonSantos @LuanFreitasRibeiro @LeonardoPedrosa @nilson-teodoro @colussicode @JoaoNascSilva @renebentes 
![ClassDiagram_V1 1](https://user-images.githubusercontent.com/31799846/117061295-e99b7880-ad19-11eb-952b-2754fdee44ff.png)

**Comment by renebentes** [comment]
Algumas operações para mim ficou estranho estar dentro da classe. Exemplos:

- AddUserRole() não deveria estar na classe de usuários?
- GetEvents() não seria melhor ficar na classe de repositório/serviços

Estou pensando diretamente no código. Faz sentido para vocês?

**Comment by LeonardoPedrosa** [comment]
> Algumas operações para mim ficou estranho estar dentro da classe. Exemplos:
> 
> * AddUserRole() não deveria estar na classe de usuários?
> * GetEvents() não seria melhor ficar na classe de repositório/serviços
> 
> Estou pensando diretamente no código. Faz sentido para vocês?

Com relação aos métodos get, faz todo sentido ter uma interface Service ou Repository, com suas devidas implementações que trate essas chamadas genericamente, passando a entidade como parâmetro.
Como se trata apenas de um diagrama para entendimento, creio que isso seja o de menos no momento.

**Comment by JoaoNascSilva** [comment]
Levando em conta o pensamento de classes e separação arquitetural, realmente, as operações de CRUD ali no modelo ficam meio estranhas mesmo.
Imagino este caso separado em repository, service ou usecases.
Nao me recordo como representar estes casos no diagrama, faz muito, mas muito tempo que nao trabalho com estes diagramas, rs

**Comment by jenrodrigues** [comment]
Alguem consegue fazer uma nova versao com esses apontamentos? 
Confesso que estou viajando nesse diagrama de classes... :/
De repente a gente pode pegar ambos e mostrar pro Balta hoje pra ver o que ele acha.

**Comment by jenrodrigues** [comment]
Decidimos na reuniao do dia 5 de maio criar e disponibilizar aqui a versao 1.2 do diagrama de classes, constituida da mesma estrutura de entidades mas SEM os metodos, pois a distribuicao deles pelas entidades acabou gerando certa confusao quanto a arquitetura da aplicacao. 
Decidiremos junto com o Balta como a implementacao dos metodos funcionara e essa implementacao sera abordada diretamente na issue #16 . 
![ClassDiagram_V1 2](https://user-images.githubusercontent.com/31799846/117228061-2cd81300-ae10-11eb-8f86-887e85aa9bfc.png)

**Comment by jenrodrigues** [comment]
Fechando issue segundo recomendacao do Balta em 6 de maio.

**Comment by romulofgouvea** [comment]
Adicionar o tempo de duração do evento
