### ISSUE TITLE
Criar script de banco de dados no projeto da API

### ISSUE THREAD

**Issue by jenrodrigues** [andrebaltieri/AgendaEventos#61]
Origem do script: https://github.com/LuanFreitasRibeiro/AgendaConsoleApp , branch master
- Colocar o script no diretorio Scripts.
- Pedido do Balta: Mudar a criacao do campo Event.Active, de "[Active] BIT NOT NULL DEFAULT 0" para "[Active] BIT NOT NULL DEFAULT(0)" (default value entre parenteses). ATENCAO: E necessario executar o script pra confirmar que a alteracao nao vai impactar no correto funcionamento do mesmo.

**Comment by renebentes** [comment]
Encerrada com o PR #70
