### ISSUE TITLE
Criar usuario

### ISSUE THREAD

**Issue by jenrodrigues** [andrebaltieri/AgendaEventos#83]
A principio essa tarefa tratara exclusivamente da criacao de um usuario. No futuro o trabalho realizado nela sera relacionado a a user story descrita em #30 .

### Status

TASK

### Checklist
- [X] Criar metodo POST para inserir usuario

### Expected behaviour
Incuir um usuario com sucesso ou alertar erro caso um usuario nao possa ser incluido.

**Comment by renebentes** [comment]
Resolved in #103
