### ISSUE TITLE
Visualizar lista de usuarios

### ISSUE THREAD

**Issue by jenrodrigues** [andrebaltieri/AgendaEventos#84]
A principio essa tarefa tratara exclusivamente da visualizacao da lista de usuarios disponiveis. No futuro o trabalho realizado nela sera relacionado a user story descrita em #31 .

### Status
TASK

### Checklist
- [X] Adicionar metodo GET para retornar lista de usuarios
- [X] Adicionar metodo GET para retornar usuario especifico (busca por id)

### Expected behaviour
Retornar dados do usuario (ou dos usuarios) ou retornar erro caso a consulta nao possa ser realizada.

**Comment by renebentes** [comment]
Resolved in #103
