### ISSUE TITLE
Atualizar usuario

### ISSUE THREAD

**Issue by jenrodrigues** [andrebaltieri/AgendaEventos#85]
Essa tarefa foi incluida no backlog para atender a solicitacao do Balta de criarmos CRUDs para cada um dos modelos existentes.

### Status
TASK

### Checklist
- [X] Adicionar metodo PUT para atualizar um usuario especifico

### Expected behaviour
Atualizar um usuario ou retornar erro caso o usuario nao seja encontrado ou nao possa ser atualizado.

**Comment by renebentes** [comment]
Resolved in #103
