### ISSUE TITLE
Excluir usuario

### ISSUE THREAD

**Issue by jenrodrigues** [andrebaltieri/AgendaEventos#86]
A principio essa tarefa tratara exclusivamente da exclusao de um usuario. No futuro o trabalho realizado nela sera relacionado a a user story descrita em #32  .

### Status
TASK

### Checklist
- [X] Incluir metodo DELETE para excluir um usuario especifico

### Expected behaviour
Excluir usuario ou retornar erro caso o usuario desejado nao seja encontrado.

**Comment by renebentes** [comment]
Resolved in #103
